### PR TITLE
Update to v0.5.4

### PR DESCRIPTION
**Pull request by LeandroStanger**
https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Boxtron/issues/1

### CODE REVIEW

**Review by gasinvein — COMMENTED** [review]
Please test if it actually works fine.

**Comment by soredake** [comment]
Any progress on this?

**Comment by gasinvein** [comment]
I have no compatible games on my Steam account to test it with. If you can confirm that it works - I'll merge this.

bot, build

**Comment by gasinvein** [comment]
Superseded by #3

**Pull request closed without merging**
